'use client'
import {useEffect,useMemo,useState} from 'react'
import {Search,Heart,MapPin,BedDouble,Bath,Maximize2,ChevronDown,Plus,Menu,Building2,ShieldCheck} from 'lucide-react'
import {getPublishedListings,type ZikosListing} from '@/lib/zikos'

type CardListing=ZikosListing & {image:string}
const demoImages=['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80']
const cities=['Prishtina','Prizren','Ferizaj','Peja','Gjakova','Gjilan']
function displayType(type:string){return type.charAt(0).toUpperCase()+type.slice(1)}
export default function Home(){const [mode,setMode]=useState<'Buy'|'Rent'>('Buy');const [city,setCity]=useState('');const [type,setType]=useState('All types');const [max,setMax]=useState('');const [listings,setListings]=useState<CardListing[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [favorites,setFavorites]=useState<string[]>([]);const [menu,setMenu]=useState(false)
useEffect(()=>{let active=true;setLoading(true);setError('');getPublishedListings({mode:mode==='Buy'?'sale':'rent',city,propertyType:type,maxPrice:max?Number(max):undefined}).then(({data,error})=>{if(!active)return;if(error){setError(error.message);setListings([])}else setListings((data??[]).map((x,i)=>({...x,image:demoImages[i%demoImages.length]})));setLoading(false)});return()=>{active=false}},[mode,city,type,max])
const filtered=useMemo(()=>listings,[listings])
const toggle=(id:string)=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id])
return <main><header style={{borderBottom:'1px solid #e7eeeb',background:'#fff'}}><div className="container" style={{height:72,display:'flex',alignItems:'center',justifyContent:'space-between'}}><a href="#" style={{fontWeight:900,fontSize:25,color:'var(--brand)',textDecoration:'none'}}>zikos<span style={{color:'#10211d'}}>.</span></a><nav style={{display:'flex',gap:28,alignItems:'center'}}><a href="#homes" style={{color:'#10211d',textDecoration:'none'}}>Homes</a><a href="#agents" style={{color:'#10211d',textDecoration:'none'}}>Agents</a><a href="#about" style={{color:'#10211d',textDecoration:'none'}}>About</a><button className="pill" style={{background:'#fff',cursor:'pointer'}} onClick={()=>alert('Authentication is the next step.')}>Sign in</button><button onClick={()=>setMenu(!menu)} style={{display:'none',border:0,background:'transparent'}}><Menu/></button></nav></div></header>
<section className="hero"><div className="container" style={{padding:'72px 0 82px'}}><div style={{maxWidth:760}}><div style={{display:'inline-flex',gap:8,alignItems:'center',padding:'8px 12px',borderRadius:99,background:'rgba(255,255,255,.12)',fontSize:14}}><ShieldCheck size={16}/> The smarter way to find property in Kosovo</div><h1 style={{fontSize:'clamp(42px,7vw,72px)',lineHeight:1.02,letterSpacing:-2,margin:'22px 0 18px'}}>Find a place<br/>you'll love.</h1><p style={{fontSize:19,lineHeight:1.6,opacity:.86,margin:0}}>Search homes, apartments, land and commercial property from trusted local owners and agents.</p></div><div className="glass" style={{marginTop:38,borderRadius:18,padding:8,maxWidth:1000}}><div style={{display:'flex',gap:6,marginBottom:8}}>{['Buy','Rent'].map(m=><button key={m} onClick={()=>setMode(m as 'Buy'|'Rent')} style={{border:0,background:mode===m?'#e5f1ed':'transparent',color:mode===m?'var(--brand)':'#52615c',fontWeight:700,borderRadius:10,padding:'10px 18px',cursor:'pointer'}}>{m}</button>)}</div><div style={{display:'grid',gridTemplateColumns:'1.4fr 1fr 1fr auto',gap:8}}><label className="pill" style={{display:'flex',alignItems:'center',gap:10}}><MapPin size={19}/><input className="searchInput" placeholder="City or neighborhood" value={city} onChange={e=>setCity(e.target.value)}/></label><label className="pill" style={{display:'flex',alignItems:'center',gap:8}}><Building2 size={18}/><select className="searchInput" value={type} onChange={e=>setType(e.target.value)}><option>All types</option><option>Apartment</option><option>House</option><option>Villa</option><option>Land</option><option>Commercial</option><option>Office</option></select></label><label className="pill"><input className="searchInput" type="number" placeholder="Max price €" value={max} onChange={e=>setMax(e.target.value)}/></label><button onClick={()=>document.getElementById('homes')?.scrollIntoView({behavior:'smooth'})} style={{border:0,borderRadius:13,padding:'0 22px',background:'var(--brand)',color:'#fff',fontWeight:800,cursor:'pointer'}}><Search size={20}/></button></div></div></div></section>
<section id="homes" className="container" style={{padding:'54px 0'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:20,marginBottom:24}}><div><p style={{color:'var(--brand)',fontWeight:800,margin:'0 0 5px'}}>LIVE LISTINGS</p><h2 style={{fontSize:32,margin:0}}>Homes for {mode.toLowerCase()}</h2></div><div style={{color:'var(--muted)'}}>{loading?'Loading…':`${filtered.length} properties`} <ChevronDown size={16} style={{verticalAlign:'middle'}}/></div></div>{error&&<div style={{padding:18,marginBottom:20,background:'#fff3f2',borderRadius:14,color:'#9b3027'}}>Could not load listings: {error}</div>}<div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:20}}>{filtered.map(x=><article className="card" key={x.id}><div style={{position:'relative'}}><img className="listingImg" src={x.image} alt={x.title}/>{x.featured&&<span style={{position:'absolute',left:12,top:12,background:'#fff',padding:'6px 10px',borderRadius:99,fontSize:12,fontWeight:800}}>FEATURED</span>}<button onClick={()=>toggle(x.id)} aria-label="Favorite" style={{position:'absolute',right:12,top:12,width:40,height:40,border:0,borderRadius:99,background:'#fff',display:'grid',placeItems:'center',cursor:'pointer'}}><Heart size={19} fill={favorites.includes(x.id)?'currentColor':'none'}/></button></div><div style={{padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><h3 style={{margin:0,fontSize:18}}>{x.title}</h3><strong style={{whiteSpace:'nowrap'}}>€{Number(x.price).toLocaleString()}</strong></div><p style={{color:'var(--muted)',margin:'8px 0 15px',fontSize:14}}><MapPin size={14} style={{verticalAlign:'-2px'}}/> {[x.city,x.neighborhood].filter(Boolean).join(' · ')}</p><div style={{display:'flex',gap:15,color:'#52615c',fontSize:14}}>{x.bedrooms!=null&&<span><BedDouble size={16} style={{verticalAlign:'-3px'}}/> {x.bedrooms} bd</span>}{x.bathrooms!=null&&<span><Bath size={16} style={{verticalAlign:'-3px'}}/> {x.bathrooms} ba</span>}{x.area_m2!=null&&<span><Maximize2 size={15} style={{verticalAlign:'-2px'}}/> {x.area_m2} m²</span>}<span>{displayType(x.property_type)}</span></div></div></article>)}</div>{!loading&&!filtered.length&&!error&&<div style={{padding:50,textAlign:'center',background:'var(--soft)',borderRadius:18}}>No published properties yet. Owners and agents can add the first listing.</div>}</section>
<section className="container" style={{padding:'10px 0 70px'}}><div className="map" style={{height:300,borderRadius:22,position:'relative',overflow:'hidden'}}><div style={{position:'absolute',inset:0,display:'grid',placeItems:'center'}}><div className="glass" style={{padding:'18px 22px',borderRadius:16,textAlign:'center'}}><MapPin size={25} style={{color:'var(--brand)'}}/><strong style={{display:'block',marginTop:6}}>Explore properties on the map</strong><small style={{color:'var(--muted)'}}>Interactive map integration is next.</small></div></div></div></section>
<section id="agents" style={{background:'var(--soft)'}}><div className="container" style={{padding:'58px 0',display:'flex',justifyContent:'space-between',alignItems:'center',gap:30}}><div><h2 style={{fontSize:30,margin:'0 0 8px'}}>Are you an agent or owner?</h2><p style={{color:'var(--muted)',margin:0}}>List your property and reach buyers and renters across Kosovo.</p></div><button onClick={()=>alert('Listing creation is coming after authentication.')} style={{border:0,borderRadius:12,background:'var(--brand)',color:'#fff',padding:'13px 18px',fontWeight:800,cursor:'pointer'}}><Plus size={17} style={{verticalAlign:'-3px'}}/> List a property</button></div></section>
<footer id="about"><div className="container" style={{padding:'30px 0',display:'flex',justifyContent:'space-between',color:'var(--muted)',fontSize:14}}><span>© 2026 Zikos Real Estate</span><span>Built for Kosovo · Prishtina · Prizren · Ferizaj · Peja</span></div></footer><style jsx>{`@media(max-width:800px){nav a,nav .pill{display:none}nav button{display:block!important}.container{width:calc(100% - 24px)}.glass>div:last-child{grid-template-columns:1fr!important}.glass>div:last-child button{height:52px}.listingImg{height:210px}.container>div[style*="repeat(3"]{grid-template-columns:1fr!important}#agents .container{display:block!important}#agents button{margin-top:18px}.map{height:250px!important}}`}</style></main>}